
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import { Toaster } from "_/components/ui/sonner";
import MySessionProvider from "./_Components/MySessionProvider/MySessionProvider";
import CartContextProvider from "./_Contexts/CartContext/CartContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meem Store",
  description: "Generated by Meem Store",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased  `}
      >
        <MySessionProvider>
          <CartContextProvider>
            <div className=" overflow-auto">
              <Navbar />

              <div className="w-11/12 mx-auto mt-72 md:mt-54 ">
                {children}
                <Toaster />
              </div>
            
            </div>
          </CartContextProvider>
        </MySessionProvider>

        {/* <Footer/> */}
      </body>
    </html>
  );
}
